services:
  localstack:
    container_name: "my-local-test"
    image: localstack/localstack:latest  
    ports:
      - "4566:4566"           
      - "4510-4559:4510-4559"  
      - "443:443"              
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - LOCALSTACK_AUTH_TOKEN=ls-noKiREhA-tipO-0094-QOMo-vAPoxeBu2612
      - DEBUG=${DEBUG:-0}
      - PERSISTENCE=${PERSISTENCE:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      localstack: {}

networks:
  localstack:
    name: localstack